let a = 1
let b = 2
let c = a & b;
let d = a | b;
let e = a ^ b;
let f = a << 1;
let g = a >> 1;
let h = a >>> 1;
let i = a < b;
let j = a <= b;
let k = a > b;
let l = a >= b;
let m = a == b;
let n = a != b;
let o = a === b;
let p = a !== b;
let q = a && b;
let r = a || b;
let s = !a;
let t = ~a;
let u = a + b;
let v = a - b;
let w = a * b;
let x = a / b;
let y = a % b;
let z = a ** b;
let aa = a & b;
let ab = a | b;
let ac = a ^ b;
let ad = a << b;
let ae = a >> b;
let af = a >>> b;
let ag = a++;
let ah = a--;
let ai = ++a;
let aj = --a;
let ak = a += b;
let al = a -= b;
let am = a *= b;
let an = a /= b;
let ao = a %= b;
let ap = a **= b;
let aq = a &= b;
let ar = a |= b;
let as = a ^= b;
let at = a <<= b;
let au = a >>= b;
let av = a >>>= b;
let aw = a == b;
let ax = a != b;
let ay = a === b;
let az = a !== b;